
"use strict";
const KEYS={items:"pet-items-v2",cats:"pet-cats-v2",theme:"pet-theme-v2"};
const defaults={income:["เงินเดือน","โบนัส","ค่าคอมมิชชั่น","รายได้เสริม","อื่นๆ"],expense:["อาหาร","เดินทาง","ค่าน้ำค่าไฟ","อินเทอร์เน็ต","ช้อปปิ้ง","สุขภาพ","การศึกษา","การลงทุน","อื่นๆ"]};
const samples=[{id:"s1",date:"2026-10-01",type:"income",category:"เงินเดือน",amount:48000,detail:"เงินเดือนประจำเดือน"},{id:"s2",date:"2026-10-01",type:"expense",category:"อาหาร",amount:180,detail:"อาหารกลางวัน"},{id:"s3",date:"2026-09-29",type:"expense",category:"เดินทาง",amount:950,detail:"เติมน้ำมัน"},{id:"s4",date:"2026-09-25",type:"income",category:"รายได้เสริม",amount:3500,detail:"งานพิเศษ"},{id:"s5",date:"2026-09-22",type:"expense",category:"ค่าน้ำค่าไฟ",amount:1650,detail:"ค่าไฟประจำเดือน"},{id:"s6",date:"2026-08-30",type:"expense",category:"การลงทุน",amount:5000,detail:"กองทุนรวม"}];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function safeRead(key,fallback){try{const x=JSON.parse(localStorage.getItem(key));return x??fallback}catch{return fallback}}
let items=safeRead(KEYS.items,null)||structuredClone(samples),cats=safeRead(KEYS.cats,null)||structuredClone(defaults),editing=null,catType="expense",editingCat=null,charts={};
const money=n=>new Intl.NumberFormat("th-TH",{style:"currency",currency:"THB",minimumFractionDigits:2}).format(n);
const today=()=>{const d=new Date(),z=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`};
const dateTH=s=>{if(!s)return "-";const [y,m,d]=s.split("-");return `${d}/${m}/${y}`};
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
function saveAll(){localStorage.setItem(KEYS.items,JSON.stringify(items));localStorage.setItem(KEYS.cats,JSON.stringify(cats))}
let toastTimer;function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove("show"),2300)}
function esc(v){const d=document.createElement("div");d.textContent=String(v??"");return d.innerHTML}
function categoryOptions(){const type=$("#type").value,current=$("#category").value;$("#category").innerHTML=cats[type].map(x=>`<option>${esc(x)}</option>`).join("");if(cats[type].includes(current))$("#category").value=current;const all=[...new Set([...cats.income,...cats.expense])];$("#filterCategory").innerHTML='<option value="all">ทุกหมวดหมู่</option>'+all.map(x=>`<option>${esc(x)}</option>`).join("")}
function filtered(){const q=$("#search").value.trim().toLowerCase(),fc=$("#filterCategory").value,start=$("#startDate").value,end=$("#endDate").value,sort=$("#sort").value;return items.filter(x=>(!q||`${x.detail} ${x.category} ${x.amount}`.toLowerCase().includes(q))&&(fc==="all"||x.category===fc)&&(!start||x.date>=start)&&(!end||x.date<=end)).sort((a,b)=>sort==="new"?b.date.localeCompare(a.date):sort==="old"?a.date.localeCompare(b.date):sort==="high"?b.amount-a.amount:a.amount-b.amount)}
function actions(x){return `<div class="row-actions"><button class="small-btn edit" data-id="${x.id}"><i class="fa-solid fa-pen"></i> แก้ไข</button><button class="small-btn delete" data-id="${x.id}"><i class="fa-solid fa-trash"></i> ลบ</button></div>`}
function render(){const income=items.filter(x=>x.type==="income").reduce((s,x)=>s+x.amount,0),expense=items.filter(x=>x.type==="expense").reduce((s,x)=>s+x.amount,0);$("#totalIncome").textContent=money(income);$("#totalExpense").textContent=money(expense);$("#balance").textContent=money(income-expense);$("#totalCount").textContent=`${items.length} รายการ`;const list=filtered();$("#visibleCount").textContent=`${list.length} รายการ`;$("#empty").hidden=!!list.length;$("#tableBody").innerHTML=list.map(x=>`<tr><td>${dateTH(x.date)}</td><td><span class="badge ${x.type}">${x.type==="income"?"รายรับ":"รายจ่าย"}</span></td><td>${esc(x.category)}</td><td class="amount ${x.type}">${x.type==="income"?"+":"-"}${money(x.amount)}</td><td>${esc(x.detail||"-")}</td><td>${actions(x)}</td></tr>`).join("");$("#cardList").innerHTML=list.map(x=>`<article class="transaction-card"><div class="row"><div><span class="badge ${x.type}">${x.type==="income"?"รายรับ":"รายจ่าย"}</span><strong> ${esc(x.category)}</strong><small> ${dateTH(x.date)}</small></div><strong class="amount ${x.type}">${x.type==="income"?"+":"-"}${money(x.amount)}</strong></div><p>${esc(x.detail||"ไม่มีรายละเอียด")}</p>${actions(x)}</article>`).join("");renderCharts(income,expense)}
function chart(id,config){charts[id]?.destroy();charts[id]=new Chart($("#"+id),config)}
function renderCharts(income,expense){const text=getComputedStyle(document.body).getPropertyValue("--muted").trim(),grid=getComputedStyle(document.body).getPropertyValue("--line").trim();Chart.defaults.color=text;const base={responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom"}}};chart("compareChart",{type:"bar",data:{labels:["ทั้งหมด"],datasets:[{label:"รายรับ",data:[income],backgroundColor:"#10b981",borderRadius:8},{label:"รายจ่าย",data:[expense],backgroundColor:"#f43f5e",borderRadius:8}]},options:{...base,scales:{y:{beginAtZero:true,grid:{color:grid}}}}});const p={};items.filter(x=>x.type==="expense").forEach(x=>p[x.category]=(p[x.category]||0)+x.amount);chart("categoryChart",{type:"doughnut",data:{labels:Object.keys(p),datasets:[{data:Object.values(p),backgroundColor:["#f43f5e","#fb923c","#facc15","#84cc16","#14b8a6","#38bdf8","#6366f1","#a855f7","#ec4899"]}]},options:{...base,cutout:"62%"}});const m={};items.forEach(x=>{const k=x.date.slice(0,7);m[k]??={income:0,expense:0};m[k][x.type]+=x.amount});const keys=Object.keys(m).sort().slice(-6);chart("monthlyChart",{type:"line",data:{labels:keys.map(k=>{const [y,mo]=k.split("-");return new Intl.DateTimeFormat("th-TH",{month:"short",year:"2-digit"}).format(new Date(+y,+mo-1,1))}),datasets:[{label:"รายรับ",data:keys.map(k=>m[k].income),borderColor:"#10b981",backgroundColor:"#10b981",tension:.3},{label:"รายจ่าย",data:keys.map(k=>m[k].expense),borderColor:"#f43f5e",backgroundColor:"#f43f5e",tension:.3}]},options:{...base,scales:{y:{beginAtZero:true,grid:{color:grid}}}}})}
function clearForm(){editing=null;$("#transactionForm").reset();$("#date").value=today();$("#type").value="expense";categoryOptions();$("#formTitle").textContent="เพิ่มรายการใหม่";$("#saveText").textContent="บันทึกข้อมูล"}
function ask(msg,fn){$("#confirmMessage").textContent=msg;$("#confirmModal").hidden=false;$("#confirmYes").onclick=()=>{$("#confirmModal").hidden=true;fn()}}
function renderCatList(){$("#categoryList").innerHTML=cats[catType].map(c=>`<div class="cat-row"><span>${esc(c)}</span><div class="row-actions"><button class="small-btn cat-edit" data-name="${esc(c)}"><i class="fa-solid fa-pen"></i></button><button class="small-btn delete cat-delete" data-name="${esc(c)}"><i class="fa-solid fa-trash"></i></button></div></div>`).join("")}
document.addEventListener("DOMContentLoaded",()=>{document.body.classList.toggle("dark",localStorage.getItem(KEYS.theme)==="dark");$("#themeBtn i").className=document.body.classList.contains("dark")?"fa-solid fa-sun":"fa-solid fa-moon";clearForm();render();
$("#transactionForm").onsubmit=e=>{e.preventDefault();const amount=Number($("#amount").value),rec={date:$("#date").value,type:$("#type").value,category:$("#category").value,amount,detail:$("#detail").value.trim()};if(!rec.date||!rec.type||!rec.category||$("#amount").value==="")return toast("กรุณากรอกข้อมูลที่จำเป็นให้ครบ");if(!Number.isFinite(amount)||amount<=0)return toast("จำนวนเงินต้องมากกว่า 0");if(editing){items=items.map(x=>x.id===editing?{...rec,id:editing}:x);toast("แก้ไขข้อมูลเรียบร้อย")}else{items.unshift({...rec,id:uid()});toast("บันทึกข้อมูลสำเร็จ")}saveAll();clearForm();render()};
$("#clearBtn").onclick=clearForm;$("#type").onchange=categoryOptions;["#search","#filterCategory","#startDate","#endDate","#sort"].forEach(s=>$(s).addEventListener(s==="#search"?"input":"change",render));$("#resetFilter").onclick=()=>{$("#search").value="";$("#filterCategory").value="all";$("#startDate").value="";$("#endDate").value="";$("#sort").value="new";render()};
document.body.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.classList.contains("edit")){const x=items.find(x=>x.id===b.dataset.id);editing=x.id;$("#date").value=x.date;$("#type").value=x.type;categoryOptions();$("#category").value=x.category;$("#amount").value=x.amount;$("#detail").value=x.detail;$("#formTitle").textContent="แก้ไขรายการ";$("#saveText").textContent="บันทึกการแก้ไข";scrollTo({top:0,behavior:"smooth"})}if(b.classList.contains("delete")&&!b.classList.contains("cat-delete")){ask("ยืนยันการลบรายการนี้หรือไม่?",()=>{items=items.filter(x=>x.id!==b.dataset.id);saveAll();render();toast("ลบข้อมูลเรียบร้อย")})}if(b.classList.contains("cat-edit")){editingCat=b.dataset.name;$("#categoryName").value=editingCat;$("#saveCategory").textContent="บันทึก"}if(b.classList.contains("cat-delete")){const n=b.dataset.name;if(items.some(x=>x.type===catType&&x.category===n))return toast("ไม่สามารถลบหมวดหมู่ที่มีรายการใช้งานอยู่");if(cats[catType].length<=1)return toast("ต้องมีอย่างน้อย 1 หมวดหมู่");ask(`ยืนยันการลบหมวดหมู่ “${n}” หรือไม่?`,()=>{cats[catType]=cats[catType].filter(x=>x!==n);saveAll();categoryOptions();renderCatList();toast("ลบหมวดหมู่เรียบร้อย")})}});
$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem(KEYS.theme,document.body.classList.contains("dark")?"dark":"light");$("#themeBtn i").className=document.body.classList.contains("dark")?"fa-solid fa-sun":"fa-solid fa-moon";render()};$("#categoryBtn").onclick=()=>{$("#categoryModal").hidden=false;renderCatList()};$("#closeModal").onclick=()=>$("#categoryModal").hidden=true;$("#confirmNo").onclick=()=>$("#confirmModal").hidden=true;$$('[data-cat-type]').forEach(b=>b.onclick=()=>{catType=b.dataset.catType;editingCat=null;$("#categoryName").value="";$("#saveCategory").textContent="เพิ่ม";$$('[data-cat-type]').forEach(x=>x.classList.toggle("active",x===b));renderCatList()});$("#saveCategory").onclick=()=>{const n=$("#categoryName").value.trim();if(!n)return toast("กรุณาระบุชื่อหมวดหมู่");if(cats[catType].some(x=>x.toLowerCase()===n.toLowerCase()&&x!==editingCat))return toast("มีหมวดหมู่นี้แล้ว");if(editingCat){cats[catType]=cats[catType].map(x=>x===editingCat?n:x);items=items.map(x=>x.type===catType&&x.category===editingCat?{...x,category:n}:x);toast("แก้ไขหมวดหมู่เรียบร้อย")}else{cats[catType].push(n);toast("เพิ่มหมวดหมู่สำเร็จ")}editingCat=null;$("#categoryName").value="";$("#saveCategory").textContent="เพิ่ม";saveAll();categoryOptions();renderCatList();render()};
});
